# Generated by Django 2.1.2 on 2018-11-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institutions',
            new_name='Institution',
        ),
    ]
