# Generated by Django 2.1.2 on 2018-11-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20181101_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_metadata',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='institution',
            table='institution',
        ),
        migrations.AlterModelTable(
            name='slide',
            table='slide',
        ),
        migrations.AlterModelTable(
            name='slide_tag',
            table='slide_tag',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='user_metadata',
            table='user_metadata',
        ),
    ]
