# Generated by Django 2.1.2 on 2018-11-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20181102_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.User')),
            ],
            options={
                'db_table': 'affiliation',
            },
        ),
    ]
