# Generated by Django 2.1.2 on 2018-11-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('user', 'institution')},
        ),
        migrations.AlterUniqueTogether(
            name='slide_tag',
            unique_together={('slide', 'tag')},
        ),
    ]
