# Generated by Django 2.1.2 on 2018-11-02 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_slide_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='last_mod',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
