# Generated by Django 2.1.2 on 2018-11-02 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_slide_last_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user_metadata',
            name='joined_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
