# Generated by Django 2.1.2 on 2018-11-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_auto_20181102_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
