# Generated by Django 2.1.2 on 2019-01-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0010_auto_20181104_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide_id',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'slide_id',
            },
        ),
        migrations.AlterField(
            model_name='slide',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slide',
            name='thumbnail',
            field=models.URLField(unique=True),
        ),
    ]
